--------------------------------------------------------
-- Missing Oracle procedures required by the backend
-- Run this after 2026-06-11.sql.
--------------------------------------------------------
SET DEFINE OFF;

--------------------------------------------------------
-- Sync identity counters after imported explicit IDs
--------------------------------------------------------

ALTER TABLE users
MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE accounts
MODIFY account_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE transactions
MODIFY transaction_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE subscriptions
MODIFY subscription_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE budgets
MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

--------------------------------------------------------
-- Accounts
--------------------------------------------------------

CREATE OR REPLACE PROCEDURE get_user_accounts_proc (
    p_user_id IN NUMBER,
    p_result  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT account_id AS id,
               account_name,
               account_type,
               balance,
               COALESCE(card_number, card_number_masked) AS card_number,
               expiry_date,
               color_theme,
               CAST(NULL AS TIMESTAMP) AS created_at
        FROM accounts
        WHERE user_id = p_user_id
        ORDER BY account_id;
END;
/

CREATE OR REPLACE PROCEDURE add_account_proc (
    p_user_id       IN  NUMBER,
    p_account_name  IN  VARCHAR2,
    p_account_type  IN  VARCHAR2,
    p_balance       IN  NUMBER,
    p_card_number   IN  VARCHAR2 DEFAULT NULL,
    p_expiry_date   IN  VARCHAR2 DEFAULT NULL,
    p_color_theme   IN  VARCHAR2 DEFAULT NULL,
    p_account_id    OUT NUMBER
) AS
BEGIN
    INSERT INTO accounts
        (user_id, account_name, account_type, balance, card_number,
         card_number_masked, expiry_date, color_theme)
    VALUES
        (p_user_id, p_account_name, p_account_type, p_balance, p_card_number,
         p_card_number, p_expiry_date, p_color_theme)
    RETURNING account_id INTO p_account_id;

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE delete_account_proc (
    p_account_id    IN  NUMBER,
    p_user_id       IN  NUMBER,
    p_rows_affected OUT NUMBER
) AS
BEGIN
    DELETE FROM transactions
    WHERE account_id = p_account_id
      AND user_id = p_user_id;

    DELETE FROM accounts
    WHERE account_id = p_account_id
      AND user_id = p_user_id;

    p_rows_affected := SQL%ROWCOUNT;
    COMMIT;
END;
/

--------------------------------------------------------
-- Transactions
--------------------------------------------------------

CREATE OR REPLACE PROCEDURE add_transaction_proc (
    p_user_id          IN  NUMBER,
    p_account_id       IN  NUMBER,
    p_description      IN  VARCHAR2,
    p_category         IN  VARCHAR2,
    p_amount           IN  NUMBER,
    p_transaction_type IN  VARCHAR2,
    p_status           OUT VARCHAR2
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM accounts
    WHERE account_id = p_account_id
      AND user_id = p_user_id;

    IF v_count = 0 THEN
        p_status := 'ACCOUNT_NOT_FOUND';
        RETURN;
    END IF;

    INSERT INTO transactions
        (account_id, user_id, description, category, amount, type)
    VALUES
        (p_account_id, p_user_id, p_description, p_category, p_amount,
         p_transaction_type);

    COMMIT;
    p_status := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = -20001 THEN
            p_status := 'INSUFFICIENT_BALANCE';
        ELSE
            p_status := 'FAILED';
        END IF;
END;
/

CREATE OR REPLACE PROCEDURE get_user_transactions_proc (
    p_user_id IN NUMBER,
    p_result  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        SELECT transaction_id AS id,
               user_id,
               account_id,
               description AS title,
               category,
               amount,
               type AS transaction_type,
               transaction_date
        FROM transactions
        WHERE user_id = p_user_id
        ORDER BY transaction_date DESC, transaction_id DESC;
END;
/

--------------------------------------------------------
-- Settings / Profile
--------------------------------------------------------

CREATE OR REPLACE PROCEDURE get_profile_proc (
    p_user_id       IN  NUMBER,
    p_full_name     OUT VARCHAR2,
    p_email         OUT VARCHAR2,
    p_profile_photo OUT CLOB,
    p_status        OUT VARCHAR2
) AS
BEGIN
    SELECT full_name, email, profile_photo
    INTO p_full_name, p_email, p_profile_photo
    FROM users
    WHERE id = p_user_id;

    p_status := 'SUCCESS';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_status := 'NOT_FOUND';
    WHEN OTHERS THEN
        p_status := 'ERROR';
END;
/

CREATE OR REPLACE PROCEDURE update_profile_proc (
    p_user_id        IN  NUMBER,
    p_full_name      IN  VARCHAR2,
    p_profile_photo  IN  CLOB,
    p_rows_affected  OUT NUMBER
) AS
BEGIN
    UPDATE users
    SET full_name = p_full_name,
        profile_photo = p_profile_photo
    WHERE id = p_user_id;

    p_rows_affected := SQL%ROWCOUNT;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE get_user_password_hash_proc (
    p_user_id       IN  NUMBER,
    p_password_hash OUT VARCHAR2,
    p_status        OUT VARCHAR2
) AS
BEGIN
    SELECT password_hash
    INTO p_password_hash
    FROM users
    WHERE id = p_user_id;

    p_status := 'SUCCESS';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_status := 'NOT_FOUND';
    WHEN OTHERS THEN
        p_status := 'ERROR';
END;
/

CREATE OR REPLACE PROCEDURE change_password_proc (
    p_user_id       IN  NUMBER,
    p_password_hash IN  VARCHAR2,
    p_status        OUT VARCHAR2
) AS
BEGIN
    UPDATE users
    SET password_hash = p_password_hash
    WHERE id = p_user_id;

    IF SQL%ROWCOUNT > 0 THEN
        COMMIT;
        p_status := 'SUCCESS';
    ELSE
        p_status := 'NOT_FOUND';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
END;
/
